packages:
  - apps/*
  - packages/*
  - services/*

enablePrePostScripts: true

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp

onlyBuiltDependencies:
  - ' '
  - '"'
  - ','
  - /
  - '@'
  - '@nestjs/core'
  - '['
  - ']'
  - a
  - b
  - c
  - d
  - e
  - g
  - h
  - i
  - l
  - m
  - n
  - p
  - r
  - s
  - t
  - u
